// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorBakery.Data;

namespace RazorBakery.Data.Migrations
{
    [DbContext(typeof(RazorBakeryContext))]
    [Migration("20190506124845_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorBakery.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeImagen")
                        .HasColumnName("ImageFileName");

                    b.Property<decimal>("Preco");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Uma Breve descricao do produto",
                            Nome = "Bolo de Cenoura",
                            NomeImagen = "boloCenoura.jpg",
                            Preco = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Uma Breve descricao do produto",
                            Nome = "Torta de Limão",
                            NomeImagen = "tortaLimao.jpg",
                            Preco = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Uma Breve descricao do produto",
                            Nome = "Cupcakes",
                            NomeImagen = "cupcakes.jpg",
                            Preco = 5.99m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Uma Breve descricao do produto",
                            Nome = "Pao",
                            NomeImagen = "pao.jpg",
                            Preco = 1.49m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = " Uma Breve descricao do produto",
                            Nome = "Torta de Pera",
                            NomeImagen = "tortaPera.jpg",
                            Preco = 5.99m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Uma Breve descricao do produto",
                            Nome = "Bolo de Chocolate ",
                            NomeImagen = "boloChocolate.jpg",
                            Preco = 8.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
